version: "3.8"

services:
  # Laravel Backend (PHP)
  app:
    build:
      context: ./docker/php
    volumes:
      - ./server:/var/www
      - ./server/.env:/var/www/.env # Optional: make .env persistent
    depends_on:
      - mysql
    working_dir: /var/www
    command: >
      sh -c "
        if [ ! -f .env ]; then cp .env.example .env; fi &&
        php artisan config:clear &&
        php artisan key:generate &&
        php artisan jwt:secret --force &&
        php artisan migrate --force &&
        php artisan serve --host=0.0.0.0 --port=8000
      "
    ports:
      - "8000:8000"
    networks:
      - app-network

  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: digitek_db
      MYSQL_ROOT_PASSWORD: urehf3034
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

  # Nginx Server
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./server:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - frontend
    networks:
      - app-network

  # React Frontend (Vite)
  frontend:
    image: node:20
    working_dir: /app
    volumes:
      - ./client/digitek:/app
    command: sh -c "npm install && npm run dev -- --host"
    ports:
      - "5173:5173"
    networks:
      - app-network

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: urehf3034
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
